// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmY8GKAmSto0DxlEDwavogHPtEnrZBkjU',
    appId: '1:628298877172:web:15f2e7d650e8cd810376a1',
    messagingSenderId: '628298877172',
    projectId: 'd-sync-muds01',
    authDomain: 'd-sync-muds01.firebaseapp.com',
    storageBucket: 'd-sync-muds01.firebasestorage.app',
    measurementId: 'G-6SVY8TSHMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6dm2NEL4r6Xdqly18sXkIyFiJ0mG-TiU',
    appId: '1:628298877172:android:4a8440c5952915050376a1',
    messagingSenderId: '628298877172',
    projectId: 'd-sync-muds01',
    storageBucket: 'd-sync-muds01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYwvRZwb3e_6NxAuRNQB7btD1X5OfXeSg',
    appId: '1:628298877172:ios:5f52db1d21525deb0376a1',
    messagingSenderId: '628298877172',
    projectId: 'd-sync-muds01',
    storageBucket: 'd-sync-muds01.firebasestorage.app',
    iosBundleId: 'com.tatsuishi.workoutapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYwvRZwb3e_6NxAuRNQB7btD1X5OfXeSg',
    appId: '1:628298877172:ios:25154bb6172b395b0376a1',
    messagingSenderId: '628298877172',
    projectId: 'd-sync-muds01',
    storageBucket: 'd-sync-muds01.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmY8GKAmSto0DxlEDwavogHPtEnrZBkjU',
    appId: '1:628298877172:web:1658833e3a1db1500376a1',
    messagingSenderId: '628298877172',
    projectId: 'd-sync-muds01',
    authDomain: 'd-sync-muds01.firebaseapp.com',
    storageBucket: 'd-sync-muds01.firebasestorage.app',
    measurementId: 'G-KB16MK2R8Z',
  );
}
